services:
  - type: web
    name: anomaly-app
    runtime: docker
    rootDir: localstack-springboot
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: local
      - key: APP_ANOMALY_PIPELINE_MODE
        value: statistical
      - key: APP_AWS_REGION
        value: us-east-1
      - key: APP_AWS_ACCESS_KEY
        value: test
      - key: APP_AWS_SECRET_KEY
        value: test
      - key: APP_AWS_ENDPOINT
        value: http://localhost:4566